theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position:  after-hero
  posts:
    default_image: false
    index:
      show_categories: false
      show_author: false
      truncate_description: 200 # Set to 0 to disable truncate
      layout: grid